<?xml version="1.0"?>
<package format="3">
  <name>ur3_write_m</name>
  <version>0.1.0</version>
  <description>Draws the letter M with a UR3 end effector using MoveIt 2 Cartesian paths.</description>
  <maintainer email="minh@example.com">Minh</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>moveit_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>ur_moveit_config</depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>ur_simulation_gz</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export><build_type>ament_cmake</build_type></export>
</package>
